name: build

on:
  schedule:
    - cron: "42 6 * * *"

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.result.outputs.tag }}

    steps:
      - name: Get upstream tag
        uses: oprypin/find-latest-tag@v1
        id: upstream_tag
        with:
          repository: rclone/rclone
          releases-only: true

      - name: Upstream tag ${{ steps.upstream_tag.outputs.tag }}
        run: echo "Upstream tag ${{ steps.upstream_tag.outputs.tag }}"

      - name: Get downstream tag
        uses: oprypin/find-latest-tag@v1
        id: downstream_tag
        continue-on-error: true
        with:
          repository: ${{ github.repository }}

      - name: Downstream tag ${{ steps.downstream_tag.outputs.tag }}
        run: echo "Downstream tag ${{ steps.downstream_tag.outputs.tag }}"

      - name: Result
        id: result
        run: |
          if [[ "${{ steps.upstream_tag.outputs.tag }}" == "${{ steps.downstream_tag.outputs.tag }}" ]]
          then
            echo 'Build not required.'
          else
            echo 'Build is required.'
            echo tag=${{ steps.upstream_tag.outputs.tag }} >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: windows-latest
    needs: check
    if: needs.check.outputs.tag != ''

    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          $tag = "${{ needs.check.outputs.tag }}".TrimStart("v")
          $version = [version]::new($tag)
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "versionMajor=$($version.Major)" >> $env:GITHUB_OUTPUT
          echo "versionMinor=$($version.Minor)" >> $env:GITHUB_OUTPUT
          echo "versionBuild=$($version.Build)" >> $env:GITHUB_OUTPUT

      - name: Setup wix
        run: |
          dotnet.exe tool install --global wix

          wix.exe extension add WixToolset.UI.wixext --global

          Invoke-RestMethod -Uri https://www.nuget.org/api/v2/package/WixToolset.Heat -OutFile .\WixToolset.Heat.nupkg -ErrorAction Stop
          Expand-Archive .\WixToolset.Heat.nupkg -DestinationPath .\heat -ErrorAction Stop
          Get-ChildItem -Path .\heat -Recurse |
            Where-Object { $_.FullName.EndsWith('x64\heat.exe') } |
            Select-Object -ExpandProperty DirectoryName |
            Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Download rclone
        run: |
          gh.exe release download ${{ needs.check.outputs.tag }} --pattern '*-windows-amd64.zip' --repo rclone/rclone
          Get-ChildItem
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract rclone
        run: |
          New-Item -Name tmp -ItemType Directory -ErrorAction Stop
          Expand-Archive -Path '*-windows-amd64.zip' -DestinationPath tmp -ErrorAction Stop
          Get-ChildItem -Path tmp -Recurse
          New-Item -Name build -ItemType Directory -ErrorAction Stop
          Get-ChildItem -Path tmp -Include '*.exe','*.html' -Recurse |Move-Item -Destination ./build -ErrorAction Stop

      - name: Harvest installer
        run: |
          heat.exe `
            dir `
            build `
            -nologo `
            -ag `
            -cg ProductComponents `
            -dr INSTALLDIR `
            -g1 `
            -srd `
            -sfrag `
            -sreg `
            -var var.ProductSource `
            -o build\Fragment.wxs

      - name: Build installer
        run: |
          wix.exe `
            build `
            -arch x64 `
            -src build\Fragment.wxs src\Product.wxs `
            -d ProductSource=build `
            -d ProductVersion="${{ steps.version.outputs.version }}" `
            -ext WixToolset.UI.wixext `
            -out rclone.msi

      - name: Update installer
        run: |
          $path = Resolve-Path 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x86\msiinfo.exe' -ErrorAction Stop

          & $path rclone.msi -t "Rclone for Windows" -o "Rclone v${{ steps.version.outputs.version }}"

      - name: Validate installer
        run: wix.exe msi validate rclone.msi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rclone-msi
          path: ./rclone.msi
          if-no-files-found: error

      - name: Test installer
        run: |
          $process = Start-Process msiexec.exe -ArgumentList '/i','rclone.msi','/qn' -Wait -NoNewWindow -PassThru -ErrorAction Stop
          if ($process.ExitCode -ne 0)
          {
              throw 'Non zero exit code: "{0}".' -f $process.ExitCode
          }

          $path = Join-Path $env:ProgramFiles 'rclone\rclone.exe'
          & $path version

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: rclone.msi
          tag: ${{ needs.check.outputs.tag }}
          body: Rclone Windows build packaged as an msi.
